name: 'GitHub Enterprise Project Automation+'
description: 'Fork of the github-project-automation-plus action to test the change to octokit to use GHES APIs'
author: 'Simon Farrow'
inputs:
  repo-token:
    description: 'The GH_TOKEN secret can be passed in using {{ secrets.GH_TOKEN }}'
    required: true
  project:
    description: 'The name of the GitHub Project'
    required: true
  column:
    description: 'The name of the column to move the issue or pull request to'
    required: true
  action:
    description: |
      Can be `update`, `delete` or `archive` or `add`. This determines the type of the action
      to be performed on the card
    required: false
    default: "update"
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'cpu'
  color: 'gray-dark'
